echo compiling ...
sudo javac -d Project1/build/ -sourcepath Project1/src/ -cp "lib/AbsoluteLayout.jar:lib/jcalendar-1.4.jar:lib/mysql-connector.jar:Project1/src/jdbc.properties" Project1/src/application/ManageMarketSystem.java
echo compile success.
echo running ... 
sudo java -cp Project1/build:lib/AbsoluteLayout.jar:lib/jcalendar-1.4.jar:lib/mysql-connector.jar:Project1/src/jdbc.properties application.ManageMarketSystem
