/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.spaceinvader;

import javax.swing.JButton;

/**
 *
 * @author nghiadv
 */
public class MenuContent extends javax.swing.JPanel {

    /**
     * Creates new form MenuContent
     */
    public MenuContent() {
        
        initComponents();
    }

    public JButton getjButtonExit() {
        return jButtonExit;
    }

    public JButton getjButtonMusic() {
        return jButtonMusic;
    }

    public JButton getjButtonNewGame() {
        return jButtonNewGame;
    }

    public JButton getjButtonResume() {
        return jButtonResume;
    }

    public JButton getjButtonScore() {
        return jButtonScore;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonResume = new javax.swing.JButton();
        jButtonNewGame = new javax.swing.JButton();
        jButtonMusic = new javax.swing.JButton();
        jButtonScore = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();

        jButtonResume.setText("Resume");

        jButtonNewGame.setText("NewGame");

        jButtonMusic.setText("Music");

        jButtonScore.setText("HighScore");

        jButtonExit.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNewGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonResume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButtonResume)
                .addGap(38, 38, 38)
                .addComponent(jButtonNewGame)
                .addGap(29, 29, 29)
                .addComponent(jButtonMusic)
                .addGap(29, 29, 29)
                .addComponent(jButtonScore)
                .addGap(30, 30, 30)
                .addComponent(jButtonExit)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonMusic;
    private javax.swing.JButton jButtonNewGame;
    private javax.swing.JButton jButtonResume;
    private javax.swing.JButton jButtonScore;
    // End of variables declaration//GEN-END:variables
}
