/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listview;

import java.util.ArrayList;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.MyUtils.ObjectWithFile;
import model.connectDatabase.ConnectAccount;
import model.connectDatabase.ConnectImportReceipt;
import model.employee.Account;
import model.employee.Importer;
import model.market.Supplier;
import model.product.ImportItem;
import model.product.ImportReceipt;
import model.product.Product;

/**
 *
 * @author leo
 */
public class ImporterView extends javax.swing.JFrame {
    private Importer importer;
    private ArrayList<Supplier> suppliers;
    private ArrayList<ImportItem> items;
    private String[] columnNames;
    private boolean isInsert;
    /**
     * Creates new form ImporterView
     */
    public ImporterView() {
        initComponents();
    }

    public ImporterView(Importer im, ArrayList<Supplier> sup) {
       this.importer = im;
       this.suppliers = sup;
       initComponents();
       settingLanguage();
       lblImporterName.setText(importer.getName());
       setImportTab();
       MyClock mc = new MyClock(lblClock);
       mc.start();
       txtFolderPath.setText(ObjectWithFile.getSavedDirectory(ObjectWithFile.IMPORT_OPTION));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        importTab = new javax.swing.JPanel();
        lblPTime = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        importItemTb = new javax.swing.JTable();
        lblPName = new javax.swing.JLabel();
        lblImPrice = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblETime = new javax.swing.JLabel();
        lblProducer = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtImportPrice = new javax.swing.JTextField();
        txtProducer = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        lblSupplier = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnPrint = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblTotalValue = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblSelect = new javax.swing.JLabel();
        txtFolderPath = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        lblChange = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblPwd = new javax.swing.JLabel();
        lblNewUser = new javax.swing.JLabel();
        lblNewPwd1 = new javax.swing.JLabel();
        lblNewPwd2 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtPreUsername = new javax.swing.JTextField();
        pfPrePassword = new javax.swing.JPasswordField();
        pfFirstNewPassword = new javax.swing.JPasswordField();
        pfSecondNewPassword = new javax.swing.JPasswordField();
        txtNewUsername = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        lblImporterName = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        lblEName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        tabs.setName(""); // NOI18N

        lblPTime.setText("Produce Date");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        importItemTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        importItemTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importItemTbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(importItemTb);

        lblPName.setText("Name");

        lblImPrice.setText("Import Price");

        lblPrice.setText("Price");

        lblETime.setText("Expire Date");

        lblProducer.setText("Producer");

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        txtImportPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImportPriceActionPerformed(evt);
            }
        });

        txtProducer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProducerActionPerformed(evt);
            }
        });

        lblQuantity.setText("Quantity");

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        lblSupplier.setText("Supplier");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        lblTotal.setText("Total :");

        lblTotalValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalValue.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrint)
                .addGap(124, 124, 124)
                .addComponent(lblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint)
                    .addComponent(lblTotal)
                    .addComponent(lblTotalValue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout importTabLayout = new javax.swing.GroupLayout(importTab);
        importTab.setLayout(importTabLayout);
        importTabLayout.setHorizontalGroup(
            importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, importTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProducer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPTime, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(lblETime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsert)
                    .addComponent(lblSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, importTabLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(importTabLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtName)
                                    .addComponent(txtProducer, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, importTabLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(txtImportPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, importTabLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete)
                            .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(24, 24, 24)
                .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        importTabLayout.setVerticalGroup(
            importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(importTabLayout.createSequentialGroup()
                        .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnRefresh))
                        .addGap(18, 18, 18)
                        .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProducer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProducer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPTime, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblETime, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblImPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtImportPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnInsert)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        tabs.addTab("Import", importTab);
        importTab.getAccessibleContext().setAccessibleName("");

        lblSelect.setText("Select File saved Folder");

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        lblChange.setText("Change Account's info");

        lblUser.setText("User Name");

        lblPwd.setText("Password");

        lblNewUser.setText("New User Name");

        lblNewPwd1.setText("New Password");

        lblNewPwd2.setText("New Password");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNewPwd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNewPwd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNewUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFolderPath)
                            .addComponent(txtPreUsername)
                            .addComponent(pfPrePassword)
                            .addComponent(pfFirstNewPassword)
                            .addComponent(pfSecondNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(txtNewUsername))
                        .addGap(18, 18, 18)
                        .addComponent(btnBrowse)))
                .addContainerGap(443, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFolderPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse))
                .addGap(18, 18, 18)
                .addComponent(lblChange, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPreUsername)
                    .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfPrePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPwd1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfFirstNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPwd2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfSecondNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        tabs.addTab("Setting", jPanel1);

        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        lblEName.setText("Name :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblEName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblImporterName, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(63, 63, 63))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(lblClock, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImporterName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tabs, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtImportPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImportPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImportPriceActionPerformed

    private void txtProducerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProducerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProducerActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        // Check name
        ResourceBundle rb = ResourceBundle.getBundle("resourceBundle.Label");
        if (txtName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, rb.getString("InputName"));
            return;
        }
        
        // check producer
        if (txtProducer.getText().equals("")) {
            JOptionPane.showMessageDialog(null, rb.getString("InputProducerName"));
            return;
        }
        
        try {
            Integer.parseInt(txtPrice.getText());
            Integer.parseInt(txtImportPrice.getText());
            Integer.parseInt(txtQuantity.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, rb.getString("InputNumber"));
            return;
        }
        
        if (isInsert) {
            ImportItem item = new ImportItem(new Product(txtName.getText(), Integer.parseInt(txtPrice.getText()),
                txtProducer.getText(), jDateChooser1.getDate(), jDateChooser2.getDate()), 
                Integer.parseInt(txtQuantity.getText()), Integer.parseInt(txtImportPrice.getText()), 
                suppliers.get(jComboBox1.getSelectedIndex()), this.importer);
            items.add(item);
          
            
        } else {
    
            ImportItem item = items.get(importItemTb.getSelectedRow());
            item.getProduct().setName(txtName.getText());
            item.getProduct().setProducer(txtProducer.getText());
            item.getProduct().setExpireTime(jDateChooser2.getDate());
            item.getProduct().setProduceTime(jDateChooser1.getDate());
            item.getProduct().setPrice(Integer.parseInt(txtPrice.getText()));
            item.setImportPrice(Integer.parseInt(txtImportPrice.getText()));
            item.setQuantity(Integer.parseInt(txtQuantity.getText()));
          
        }
        displayTotal();
        refresh();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void refresh() {
        ResourceBundle rb = ResourceBundle.getBundle("resourceBundle.Label");
        txtName.setText(null);
        txtPrice.setText(null);
        txtImportPrice.setText(null);
        txtProducer.setText(null);
        txtQuantity.setText(null);
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
        btnDelete.setVisible(false);
        btnInsert.setText(rb.getString("Insert"));
        isInsert = true;
        displayItems();
    }
    private void importItemTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importItemTbMouseClicked
        // TODO add your handling code here:
        ResourceBundle rb = ResourceBundle.getBundle("resourceBundle.Label");
        ImportItem it = items.get(importItemTb.getSelectedRow());
        txtName.setText(it.getProduct().getName());
        txtPrice.setText("" + it.getProduct().getPrice());
        txtImportPrice.setText("" + it.getImportPrice());
        txtProducer.setText(it.getProduct().getProducer());
        txtQuantity.setText("" + it.getQuantity());
        jDateChooser1.setDate(it.getProduct().getProduceTime());
        jDateChooser2.setDate(it.getProduct().getExpireTime());
        jComboBox1.setSelectedIndex(getIndex(it.getSupplier()));
        btnDelete.setVisible(true);
        btnInsert.setText(rb.getString("Update"));
        isInsert = false;
    }//GEN-LAST:event_importItemTbMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        items.remove(importItemTb.getSelectedRow());
        displayTotal();
        refresh();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        ResourceBundle rb = ResourceBundle.getBundle("resourceBundle.Label");
        if (items.isEmpty()) {
            JOptionPane.showMessageDialog(null, rb.getString("Empty"));
            return;
        }
        ImportReceipt receipt = new ImportReceipt(items, Integer.parseInt(lblTotalValue.getText()));
        ConnectImportReceipt.saveNewImportReceipt(receipt);
        
        ObjectWithFile.printImportReceipt(receipt);
        items = new ArrayList<>();
        refresh();
        
        
        
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        ResourceBundle rb = ResourceBundle.getBundle("resourceBundle.Label");
        int option = JOptionPane.showConfirmDialog(null, rb.getString("Exit?"));
        if (option == JOptionPane.OK_OPTION) {
            this.dispose();
            new LoginView().setVisible(true);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            
            String folderPath = fileChooser.getSelectedFile().getAbsolutePath();
            txtFolderPath.setText(folderPath);
            
            ObjectWithFile.saveDirectory(folderPath, ObjectWithFile.IMPORT_OPTION);
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        ResourceBundle rb = ResourceBundle.getBundle("resourceBundle.Label");
        if (importer.getAccount().equals(
                new Account(txtPreUsername.getText(), pfPrePassword.getText()))) {
            if (txtNewUsername.getText().equals("") 
                    || pfFirstNewPassword.getText().equals("")
                    | pfSecondNewPassword.getText().equals("")) {
                JOptionPane.showMessageDialog(null, rb.getString("InputAll"));
                return;
            }
            if (pfFirstNewPassword.getText().equals(pfSecondNewPassword.getText())) {
                Account account = new Account(txtNewUsername.getText(), pfFirstNewPassword.getText());
                importer.setAccount(account);
                ConnectAccount.saveChangedAccount(account, importer.getEmployeeId());
                JOptionPane.showMessageDialog(null, "OK");
                txtPreUsername.setText(null);
                txtNewUsername.setText(null);
                pfFirstNewPassword.setText(null);
                pfPrePassword.setText(null);
                pfSecondNewPassword.setText(null);
            } else {
                JOptionPane.showMessageDialog(null, rb.getString("TwoPwdNotSame"));
            }
        } else {
            JOptionPane.showMessageDialog(null, rb.getString("InvalidAccount"));
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    
    private int getIndex(Supplier s) {
        for (int i = 0; i < suppliers.size(); i ++) {
            if (s.getSupplierId() == suppliers.get(i).getSupplierId()) {
                return i;
            }
        }
        return 0;
    }
    
    private void setImportTab () {
        setLocationRelativeTo(null);
        items = new ArrayList<>();
        btnDelete.setVisible(false);
        displayItems();
        isInsert = true;
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Supplier s : suppliers) {
            model.addElement(s.getSupplierId() + ". "+ s.getName());
        }
        jComboBox1.setModel(model);
    }
    
    private void displayItems() {
        MyModel model = new MyModel(columnNames);
        for (ImportItem it : items) {
            String[] row = {it.getProduct().getName(), "" + it.getQuantity(), "" + it.getImportPrice()};
            model.addRow(row);
        }
        displayTotal();
        importItemTb.setModel(model);
    }
    
    private void displayTotal() {
        long total = 0;
        for (ImportItem it : items) {
            total += it.getImportPrice() * it.getQuantity();
        }
        lblTotalValue.setText("" + total);
    }
    
    private void settingLanguage() {
        ResourceBundle rb = ResourceBundle.getBundle("resourceBundle.Label");
//        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(rb.getString("ProductList")));
        lblEName.setText(rb.getString("EmployeeName"));
        lblETime.setText(rb.getString("ExpiredTime"));
        lblImPrice.setText(rb.getString("ImPrice"));
        lblPName.setText(rb.getString("ProductName"));
        lblPTime.setText(rb.getString("ProducedTime"));
        lblPrice.setText(rb.getString("Price"));
        lblProducer.setText(rb.getString("Producer"));
        lblQuantity.setText(rb.getString("Quantity"));
        lblSupplier.setText(rb.getString("Supplier"));
        lblTotal.setText(rb.getString("Total"));
        columnNames = new String[] {rb.getString("ProductName"), rb.getString("Quantity"),
            rb.getString("ImPrice")};
        btnDelete.setText(rb.getString("Delete"));
        btnInsert.setText(rb.getString("Insert"));
        btnLogOut.setText(rb.getString("Logout"));
        btnPrint.setText(rb.getString("Print"));
        btnRefresh.setText(rb.getString("Refresh"));
        btnSave.setText(rb.getString("Save"));
        btnBrowse.setText(rb.getString("BrowseFile"));
        lblChange.setText(rb.getString("ChangeAccInfo"));
        lblNewPwd1.setText(rb.getString("NewPwd"));
        lblNewPwd2.setText(rb.getString("NewPwd"));
        lblNewUser.setText(rb.getString("NewUser"));
        lblUser.setText(rb.getString("Username"));
        lblPwd.setText(rb.getString("Password"));
        lblSelect.setText(rb.getString("SelectFile"));


        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JTable importItemTb;
    private javax.swing.JPanel importTab;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblEName;
    private javax.swing.JLabel lblETime;
    private javax.swing.JLabel lblImPrice;
    private javax.swing.JLabel lblImporterName;
    private javax.swing.JLabel lblNewPwd1;
    private javax.swing.JLabel lblNewPwd2;
    private javax.swing.JLabel lblNewUser;
    private javax.swing.JLabel lblPName;
    private javax.swing.JLabel lblPTime;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProducer;
    private javax.swing.JLabel lblPwd;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSelect;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalValue;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField pfFirstNewPassword;
    private javax.swing.JPasswordField pfPrePassword;
    private javax.swing.JPasswordField pfSecondNewPassword;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTextField txtFolderPath;
    private javax.swing.JTextField txtImportPrice;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNewUsername;
    private javax.swing.JTextField txtPreUsername;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProducer;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
