/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listview;

import java.util.ArrayList;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import model.MyUtils.MyDate;
import model.connectDatabase.ConnectExportReceipt;
import model.connectDatabase.ConnectImportReceipt;
import model.employee.Manager;
import model.product.ExportReceipt;
import model.product.ImportReceipt;

/**
 *
 * @author leo
 */
public class ManageInOutView extends javax.swing.JFrame {
    private Manager manager;
    String[] columnNames;
    ArrayList<ExportReceipt> exportReceipts;
    ArrayList<ImportReceipt> importReceipts;
    /**
     * Creates new form ManageInOutView
     */
    public ManageInOutView(Manager manager) {
        initComponents();
        setLocationRelativeTo(null);
        settingLanguage();
        this.manager = manager;
        this.exportReceipts = ConnectExportReceipt.getExportReceipts();
        this.importReceipts = ConnectImportReceipt.getImportReceipts();
        displayImportReceipt();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cmbOption = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        lblReceiptId = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(760, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnBack)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        cmbOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ImportReceipt", "ExportReceipt" }));
        cmbOption.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbOptionItemStateChanged(evt);
            }
        });

        lblReceiptId.setText("Input Receipt ID");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbOption, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblReceiptId, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReceiptId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addContainerGap())
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ManagerView(manager).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbOptionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbOptionItemStateChanged
        // TODO add your handling code here:
        int index = cmbOption.getSelectedIndex();
        jTextField1.setText(null);
        if (index == 0) {

            displayImportReceipt();
        } else if (index == 1) {
            displayExportReceipt();
        }
        
    }//GEN-LAST:event_cmbOptionItemStateChanged

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        int index = cmbOption.getSelectedIndex();
        int id = 0;
        
        try {
             id = Integer.parseInt(jTextField1.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Input numeric data");
            return;
        }
        MyModel model = new MyModel(columnNames);
        if (index == 0) {
           for (ImportReceipt receipt : this.importReceipts) {
               if (receipt.getId() == id) {
                    String[] row = {
                        "" + receipt.getId(),
                        MyDate.formatDate(receipt.getDate()),
                        "" + receipt.getTotal()
                    };
       
                    model.addRow(row);
                    table.setModel(model);
                    return;
               }
           }
           model.setRowCount(0);
           table.setModel(model);
        } else if (index == 1) {
            for (ExportReceipt receipt : this.exportReceipts) {
               if (receipt.getCode() == id) {
                    String[] row = {
                        "" + receipt.getCode(),
                        MyDate.formatDate(receipt.getTime()),
                        "" + receipt.getTotal()
                    };
       
                    model.addRow(row);
                    table.setModel(model);
                    return;
               }
           }
           model.setRowCount(0);
           table.setModel(model);
        }
        
        
    }//GEN-LAST:event_btnSearchActionPerformed
    
    private void displayExportReceipt() {
        MyModel model = new MyModel(columnNames);
       
        for (ExportReceipt receipt : exportReceipts) {
            String[] row = {
                "" + receipt.getCode(),
                MyDate.formatDate(receipt.getTime()),
                "" + receipt.getTotal()
            };
       
            model.addRow(row);
        }
        table.setModel(model);
        
    }
    private void displayImportReceipt() {
        MyModel model = new MyModel(columnNames);
        
        for (ImportReceipt receipt : importReceipts) {
        
            String[] row = {
                "" + receipt.getId(),
                MyDate.formatDate(receipt.getDate()),
                "" + receipt.getTotal()
            };
         
            model.addRow(row);
   
            
        }
        table.setModel(model);
    }

    private void settingLanguage() {
        ResourceBundle rb = ResourceBundle.getBundle("resourceBundle.Label");
        btnBack.setText(rb.getString("Back"));
        btnSearch.setText(rb.getString("Search"));
        lblReceiptId.setText(rb.getString("ReceiptId"));
        columnNames = new String[] {
            rb.getString("ReceiptId"),
            rb.getString("TimeCreated"),
            rb.getString("Total")
        };
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbOption;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblReceiptId;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
