/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listview;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.MyUtils.ObjectWithFile;
import model.connectDatabase.ConnectEmployee;
import model.connectDatabase.ConnectMarket;
import model.employee.Division;
import model.employee.Employee;
import model.employee.Gender;
import model.employee.Manager;
import model.market.Cost;

/**
 *
 * @author PhamThiDuyen
 */
public class ManageEmployeeView extends javax.swing.JFrame {
    private ArrayList<Employee> employees;
    private ArrayList<Employee> filterdEmployees;
    private boolean update;
    private String linkImage;
    private Manager manager;
    private String[] columnNames;
    private String saveStr;
    private String updateStr;
    /**
     * Creates new form FormQuanLiNhanVien
     */
    public ManageEmployeeView() {
        initComponents();
        
    }
    
    public ManageEmployeeView(Manager manager, ArrayList<Employee> employees) {
        this.manager = manager;
        initComponents();
        setLanguage();
        this.employees = employees;
       
        filterdEmployees = filter(employees, Division.ALL);

        displayEmployees(filterdEmployees);
        btnBrowse.setVisible(false);
        
    }
    
    public void setEmployees(ArrayList<Employee> employees) {
        this.employees = employees;
    }
    
    public ArrayList<Employee> getEmployees() {
        return employees;
    }
    
    private void displayEmployees(ArrayList<Employee> employees) {
       
        MyModel model = new MyModel(columnNames);

        for (Employee employee : employees) {
            String[] row = {"" + employee.getEmployeeId(), employee.getName(), employee.getDivision().toString()};
             model.addRow(row);
        }

       
        
        jTable1.setModel(model);
        
    }
    
    private ArrayList<Employee> filter(ArrayList<Employee> employees, Division division) {
        if (division.equals(Division.ALL)) {
            return employees;
        }
        
        ArrayList<Employee> filtered = new ArrayList<>();
        for (Employee employee : employees) {
            if (employee.getDivision().equals(division)) {
                filtered.add(employee);
            }
        }
        return filtered;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearchId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSearchName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSeach = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        btnLogout = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        imgNhanVien = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        btnBrowse = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Manage Employee");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(432, 432, 432))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee List"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Tên", "Vị Trí"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Search by ID");

        jLabel3.setText("Or by Name");

        jLabel4.setText("Division");

        btnSeach.setText("Search");
        btnSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeachActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new DefaultComboBoxModel<Division>(
            new Division[] {
                Division.ALL,
                Division.EMPLOYEE,
                Division.IMPORTER,
                Division.MANAGER,
                Division.SALESMAN,
                Division.RETIRED
            })
        );
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(btnSeach)
                .addGap(41, 41, 41)
                .addComponent(btnBack)
                .addGap(37, 37, 37)
                .addComponent(btnLogout)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnSeach)
                    .addComponent(btnBack)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee's Information"));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnPay.setText("Pay salary");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        jLabel5.setText("ID :");

        jLabel6.setText("Name:");

        jLabel7.setText("Gender:");

        jLabel8.setText("Birthday :");

        jLabel9.setText("Address:");

        jLabel10.setText("Phone:");

        jLabel11.setText("Salary base:");

        jLabel12.setText("Division:");

        txtID.setEditable(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtName.setEditable(false);

        txtAddress.setEditable(false);

        txtPhone.setEditable(false);

        txtSalary.setEditable(false);

        jComboBox1.setModel(new DefaultComboBoxModel<Gender> (new Gender[] {
            Gender.FEMALE, Gender.MALE
        }));

        imgNhanVien.setText("img");

        jComboBox2.setModel(new DefaultComboBoxModel<Division> (new Division[] {
            Division.EMPLOYEE,
            Division.IMPORTER,
            Division.MANAGER,
            Division.SALESMAN,
            Division.RETIRED
        })
    );

    btnBrowse.setText("Browse");
    btnBrowse.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBrowseActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imgNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnUpdate)
                .addComponent(btnBrowse))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGap(37, 37, 37)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtID)
                        .addComponent(txtName)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPay)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addContainerGap(154, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
            .addGap(17, 17, 17)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(12, 12, 12)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(12, 12, 12)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(11, 11, 11)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addComponent(imgNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnBrowse))
            .addGap(18, 18, 18)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnPay)
                .addComponent(btnAdd)
                .addComponent(btnUpdate))
            .addGap(52, 52, 52))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AddEmployeeView(manager).setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        resetTextFields();
        display(filterdEmployees.get(index));
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (update == false && !txtID.getText().equals("")) {
            setEditableForTextField(true);
            btnUpdate.setText(saveStr);
            btnBrowse.setVisible(true);
            update = true;
            
        } else if (update == true && !txtID.getText().equals("")) {
            
                
                Employee employee = filterdEmployees.get(jTable1.getSelectedRow());
                employee.setName(txtName.getText());
                employee.setGender((Gender) jComboBox1.getSelectedItem());
                employee.setDateOfBirth(jDateChooser1.getDate());
                employee.setAddress(txtAddress.getText());
                employee.setPhoneNumber(txtPhone.getText());
                employee.setCoefficientsSalary(Integer.parseInt(txtSalary.getText()));
                employee.setDivision((Division) jComboBox2.getSelectedItem());
                if (linkImage != null) {
                    BufferedImage img;
                    try {
                      imgNhanVien.setText(null);
                      img = ImageIO.read(new FileInputStream(linkImage));
                      employee.setImage(new ImageIcon(img));

                    } catch (IOException e) {
                      JOptionPane.showMessageDialog(null, "System Error!");

                    }
                }
                ConnectEmployee.saveChangedEmployee(employee, linkImage);

                displayEmployees(filterdEmployees);
                setEditableForTextField(false);
            
            
            btnUpdate.setText(updateStr);
            update = false;
            btnBrowse.setVisible(false);
            linkImage = null;
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void setEditableForTextField(boolean value) {
        txtAddress.setEditable(value);
      
        txtName.setEditable(value);
        txtPhone.setEditable(value);
        txtSalary.setEditable(value);
    }
    
    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileNameExtensionFilter("*.jpg", "jpg"));
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
         
          String link = chooser.getSelectedFile().getAbsolutePath();
          String extension = "";

          int i = link.lastIndexOf('.');
          if (i > 0) {
              extension = link.substring(i+1);
          }
          if (!extension.equals("jpg")) {
            JOptionPane.showMessageDialog(null, "You must choose file with .jpg extension");
            return;
          }
          linkImage = link;
          
          BufferedImage img;
          try {
            imgNhanVien.setText(null);
            img = ImageIO.read(chooser.getSelectedFile());
            Image dimg = img.getScaledInstance(imgNhanVien.getHeight(), imgNhanVien.getWidth(), Image.SCALE_SMOOTH);
            imgNhanVien.setIcon(new ImageIcon(dimg));

          } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "System Error!");
            
          }
         
          
        } else {
          return;
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeachActionPerformed
        // TODO add your handling code here:
        ResourceBundle rb = ResourceBundle.getBundle("resourceBundle.Label");

        if (!txtSearchId.getText().equals("")) {
            try {
                Integer.parseInt(txtSearchId.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, rb.getString("InputNumber") );
                return;
            }
        }
        search();
    }//GEN-LAST:event_btnSeachActionPerformed

    private void search() {
        resetTextFields();
        if (txtSearchId.getText().equals("") && txtSearchName.getText().equals("")) {
            filterdEmployees = filter(employees, (Division) jComboBox3.getSelectedItem());
            displayEmployees(filterdEmployees);
        } else if (!txtSearchId.getText().equals("")) {
            filterdEmployees = filterByID(Integer.parseInt(txtSearchId.getText()));
            displayEmployees(filterdEmployees);
        } else {
            filterdEmployees = filterByName(txtSearchName.getText());
            displayEmployees(filterdEmployees);
        }  
    }
    
    private ArrayList<Employee> filterByID(int id) {
        ArrayList<Employee> result = new ArrayList<>();
        for (Employee employee : employees) {
            if (employee.getEmployeeId() == id) {
                result.add(employee);
                return result;
            }
        }
        return result;
    }
    
    private ArrayList<Employee> filterByName(String name) {
        ArrayList<Employee> result = new ArrayList<>();
        for (Employee employee : employees) {
            if (employee.getName().contains(name)) {
                result.add(employee);
            }
        }
        return result;
    }
    
    private void resetTextFields() {
        txtID.setText(null);
        txtID.setEditable(false);
        txtAddress.setText(null);
        txtAddress.setEditable(false);
        update = false;
        btnBrowse.setVisible(false);
        btnUpdate.setText(updateStr);
        txtName.setText(null);
        txtName.setEditable(false);
        txtPhone.setText(null);
        txtPhone.setEditable(false);
        txtSalary.setText(null);
        txtSalary.setEditable(false);
        imgNhanVien.setIcon(null);
        jDateChooser1.setDate(null);
        imgNhanVien.setText("Image");
    }
    
    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        filterdEmployees = filter(employees, (Division) jComboBox3.getSelectedItem());
        displayEmployees(filterdEmployees);
        resetTextFields();
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginView().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ManagerView(manager).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        int userOption = JOptionPane.showConfirmDialog(null, "You really want to pay salary for all employees ?");
        if (userOption != JOptionPane.OK_OPTION) {
            return;
        }
        Cost paySalary = Manager.createSalaryCost(employees);
       
        ConnectMarket.saveCost(paySalary);
        ObjectWithFile.printSalaryTable(employees);
        
    }//GEN-LAST:event_btnPayActionPerformed
    
    private void display(Employee employee) {
        txtID.setText("" + employee.getEmployeeId());
        txtName.setText(employee.getName());
        jComboBox1.setSelectedItem(employee.getGender());
     
        txtAddress.setText(employee.getAddress());
        txtPhone.setText(employee.getPhoneNumber());
        txtSalary.setText("" + employee.getCoefficientsSalary());
        jComboBox2.setSelectedItem(employee.getDivision());
        jDateChooser1.setDate(employee.getDateOfBirth());
        Image dimg = employee.getImage().getImage().getScaledInstance(imgNhanVien.getWidth(), imgNhanVien.getHeight(),
        Image.SCALE_SMOOTH);
        imgNhanVien.setIcon(new ImageIcon(dimg));
    }
    
    private void setLanguage() {
        ResourceBundle resourceBundle = ResourceBundle.getBundle("resourceBundle.Label");
        jLabel1.setText(resourceBundle.getString("ManageE"));
        jLabel2.setText(resourceBundle.getString("SearchId"));
        jLabel3.setText(resourceBundle.getString("SearchName"));
        jLabel5.setText(resourceBundle.getString("ID"));
        jLabel6.setText(resourceBundle.getString("Name"));
        jLabel7.setText(resourceBundle.getString("Gender"));
        jLabel8.setText(resourceBundle.getString("Birthday"));
        jLabel9.setText(resourceBundle.getString("Address"));
        jLabel10.setText(resourceBundle.getString("Phone"));
        jLabel11.setText(resourceBundle.getString("Salarybase"));
        jLabel12.setText(resourceBundle.getString("Division"));
        btnAdd.setText(resourceBundle.getString("Add"));
        btnBack.setText(resourceBundle.getString("Back"));
        btnUpdate.setText(resourceBundle.getString("Update"));
        btnBrowse.setText(resourceBundle.getString("Browse"));
        btnLogout.setText(resourceBundle.getString("Logout"));
        btnPay.setText(resourceBundle.getString("PaySalary"));
        btnSeach.setText(resourceBundle.getString("Search"));
        columnNames = new String[] {resourceBundle.getString("ID"), 
            resourceBundle.getString("Name"), resourceBundle.getString("Division")};
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceBundle.getString("EmployeeList")));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceBundle.getString("EmployeeInfo")));
     
        saveStr = resourceBundle.getString("Save");
        updateStr = resourceBundle.getString("Update");
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnSeach;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel imgNhanVien;
    private javax.swing.JComboBox<Gender> jComboBox1;
    private javax.swing.JComboBox<Division> jComboBox2;
    private javax.swing.JComboBox<Division> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSearchId;
    private javax.swing.JTextField txtSearchName;
    // End of variables declaration//GEN-END:variables
}
