/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listview;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.MyUtils.MyDate;
import model.connectDatabase.ConnectMarket;
import model.connectDatabase.ConnectStatisticsCost;

import model.connectDatabase.ConnectStatisticsExport;
import model.connectDatabase.ConnectStatisticsImport;
import model.connectDatabase.CostResult;
import model.employee.Manager;
import model.market.Cost;
import model.market.Result;
import model.market.TypeCost;

/**
 *
 * @author anhsang
 */
public class ManageRevenueAndCostView extends javax.swing.JFrame {
    private ArrayList<Result> resultsExport;
    private ArrayList<Result> resultsImport;
    private ArrayList<CostResult> resultCost;
    private Manager manager;
    private String[] columnNames;
    private String[] columnNamesCost;
    /**
     * Creates new form GiaoDien
     */
   ManageRevenueAndCostView(Manager manager) {
        this.manager = manager;
        initComponents();
        settingLanguage();
        setLocationRelativeTo(null);
        Date from = null;
        try{
          from = MyDate.parseDateString("2015-01-01");
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        jDateChooser1.setDate(from);
        jDateChooser2.setDate(new Date());
        resultsExport = ConnectStatisticsExport.statisticsR(from, new Date(), ConnectStatisticsExport.PERDAY);
        displayResults(resultsExport, revenueTable);
        resultsImport = ConnectStatisticsImport.statisticsR(from, new Date(), ConnectStatisticsImport.PERDAY);
        displayResults(resultsImport, importTable);
        resultCost = ConnectStatisticsCost.statisticsR(from, new Date(), ConnectStatisticsCost.PERDAY);
        displayCostResults(resultCost, costTable);
        profit.setText("" + Manager.countProfit(resultsExport, resultsImport, resultCost));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dd = new javax.swing.JPanel();
        lblFrom = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblStatistics = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        pRevenue = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        revenueTable = new javax.swing.JTable();
        pCosts = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        costTable = new javax.swing.JTable();
        lblPay = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        txtTotal = new javax.swing.JTextField();
        btnExecute = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        pImport = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        importTable = new javax.swing.JTable();
        pProfit = new javax.swing.JPanel();
        lblProfit = new javax.swing.JLabel();
        profit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        dd.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblFrom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFrom.setText("From");

        lblTo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTo.setText("To");

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Per day", "Per month", "Per year" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        lblStatistics.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStatistics.setText("Statistics");

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblTitle.setText("Manage Revenue And Costs");

        javax.swing.GroupLayout ddLayout = new javax.swing.GroupLayout(dd);
        dd.setLayout(ddLayout);
        ddLayout.setHorizontalGroup(
            ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ddLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ddLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addGap(48, 48, 48))
                    .addGroup(ddLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        ddLayout.setVerticalGroup(
            ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pRevenue.setBorder(javax.swing.BorderFactory.createTitledBorder("Revenue Table"));

        revenueTable.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));
        revenueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(revenueTable);

        javax.swing.GroupLayout pRevenueLayout = new javax.swing.GroupLayout(pRevenue);
        pRevenue.setLayout(pRevenueLayout);
        pRevenueLayout.setHorizontalGroup(
            pRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRevenueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        pRevenueLayout.setVerticalGroup(
            pRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRevenueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pCosts.setBorder(javax.swing.BorderFactory.createTitledBorder("Costs Table"));

        costTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(costTable);

        lblPay.setText("Pay Cost");

        jComboBox2.setModel(new DefaultComboBoxModel<TypeCost> (new TypeCost[] {
            TypeCost.TIENDIEN,
            TypeCost.TIENNUOC,
            TypeCost.TIENTHUE})
    );

    btnExecute.setText("Execute");
    btnExecute.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnExecuteActionPerformed(evt);
        }
    });

    lblTotal.setText("Total");

    javax.swing.GroupLayout pCostsLayout = new javax.swing.GroupLayout(pCosts);
    pCosts.setLayout(pCostsLayout);
    pCostsLayout.setHorizontalGroup(
        pCostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pCostsLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pCostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pCostsLayout.createSequentialGroup()
                    .addComponent(btnExecute)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pCostsLayout.createSequentialGroup()
                    .addComponent(lblPay, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
    );
    pCostsLayout.setVerticalGroup(
        pCostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCostsLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pCostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pCostsLayout.createSequentialGroup()
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addGap(2, 2, 2))
                .addGroup(pCostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pCostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox2)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPay, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
            .addGap(18, 18, 18)
            .addComponent(btnExecute)
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(3, 3, 3))
    );

    pImport.setBorder(javax.swing.BorderFactory.createTitledBorder("Import Price Table\n"));

    importTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ));
    jScrollPane3.setViewportView(importTable);

    javax.swing.GroupLayout pImportLayout = new javax.swing.GroupLayout(pImport);
    pImport.setLayout(pImportLayout);
    pImportLayout.setHorizontalGroup(
        pImportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pImportLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    pImportLayout.setVerticalGroup(
        pImportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pImportLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pProfit.setBorder(javax.swing.BorderFactory.createTitledBorder("Profit Table"));

    lblProfit.setText("Profit\n");

    javax.swing.GroupLayout pProfitLayout = new javax.swing.GroupLayout(pProfit);
    pProfit.setLayout(pProfitLayout);
    pProfitLayout.setHorizontalGroup(
        pProfitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pProfitLayout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addComponent(lblProfit, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(50, 50, 50)
            .addComponent(profit, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    pProfitLayout.setVerticalGroup(
        pProfitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pProfitLayout.createSequentialGroup()
            .addGap(70, 70, 70)
            .addGroup(pProfitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblProfit)
                .addComponent(profit, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(dd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 15, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pCosts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pProfit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGap(24, 24, 24))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(pRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pCosts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(pImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pProfit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(40, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        int index = jComboBox1.getSelectedIndex();
        Date from = jDateChooser1.getDate();
        Date to = jDateChooser2.getDate();
        if (index == 1) {
            resultsExport = ConnectStatisticsExport.statisticsR(from, 
                to, ConnectStatisticsExport.PERMONTH);
            displayResults(resultsExport, revenueTable);
            
            resultsImport = ConnectStatisticsImport.statisticsR(from, to, 
                    ConnectStatisticsImport.PERMONTH);
            displayResults(resultsImport, importTable);
            
            resultCost = ConnectStatisticsCost.statisticsR(from, to, ConnectStatisticsCost.PERMONTH);
            displayCostResults(resultCost, costTable);
        } else if (index == 2) {
            resultsExport = ConnectStatisticsExport.statisticsR(from, 
                to, ConnectStatisticsExport.PERYEAR);
            displayResults(resultsExport, revenueTable);
            
            resultsImport = ConnectStatisticsImport.statisticsR(from, to, 
                    ConnectStatisticsImport.PERYEAR);
            displayResults(resultsImport, importTable);
            
            resultCost = ConnectStatisticsCost.statisticsR(from, to, ConnectStatisticsCost.PERYEAR);
            displayCostResults(resultCost, costTable);
        } else {
            resultsExport = ConnectStatisticsExport.statisticsR(from, 
                to, ConnectStatisticsExport.PERDAY);
            displayResults(resultsExport, revenueTable);
            
            resultsImport = ConnectStatisticsImport.statisticsR(from, to, 
                    ConnectStatisticsImport.PERDAY);
            displayResults(resultsImport, importTable);
            
            resultCost = ConnectStatisticsCost.statisticsR(from, to, ConnectStatisticsCost.PERDAY);
            displayCostResults(resultCost, costTable);
            
            profit.setText("" + Manager.countProfit(resultsExport, resultsImport, resultCost));
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteActionPerformed
        // TODO add your handling code here:
        int total = 0;
        try {
            total = Integer.parseInt(txtTotal.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Nhap tong chi phi");
            return;
        }
        
        ConnectMarket.saveCost(new Cost((TypeCost) jComboBox2.getSelectedItem(), new Date(), total));
        JOptionPane.showMessageDialog(null, "Ok");
        
        
    }//GEN-LAST:event_btnExecuteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ManagerView(manager).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed
    
    private void displayResults(ArrayList<Result> results, JTable table) {
        
        MyModel model = new MyModel(columnNames);
        for (Result rs : results) {
            String[] row = {rs.getName(), "" + rs.getValue()};
            model.addRow(row);
        }
        table.setModel(model);
    }
    
    private void displayCostResults(ArrayList<CostResult> results, JTable table) {
        
        MyModel model = new MyModel(columnNamesCost);
        for (CostResult rs : results) {
            String[] row = {rs.getName(), rs.getDate(), "" + rs.getTotal()};
            model.addRow(row);
        }
        table.setModel(model);
    }
    
    private void settingLanguage() {
        ResourceBundle rb = ResourceBundle.getBundle("resourceBundle.Label");
        btnExecute.setText(rb.getString("Execute"));
        btnBack.setText(rb.getString("Back"));
        lblFrom.setText(rb.getString("From"));
        lblTo.setText(rb.getString("To"));
        lblPay.setText(rb.getString("PayCost"));
        lblProfit.setText(rb.getString("Profit"));
        lblStatistics.setText(rb.getString("Statistics"));
        lblTitle.setText(rb.getString("ManageRC"));
        lblTotal.setText(rb.getString("Total"));
        pRevenue.setBorder(javax.swing.BorderFactory.createTitledBorder(rb.getString("RevenueTb")));
        pCosts.setBorder(javax.swing.BorderFactory.createTitledBorder(rb.getString("CostsTb")));
        pImport.setBorder(javax.swing.BorderFactory.createTitledBorder(rb.getString("ImportTb")));
        pProfit.setBorder(javax.swing.BorderFactory.createTitledBorder(rb.getString("ProfitTb")));
        columnNames = new String[] {rb.getString("Time"), rb.getString("Total")};
        columnNamesCost = new String[] {rb.getString("Name"), rb.getString("Time"), rb.getString("Total")};
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExecute;
    private javax.swing.JTable costTable;
    private javax.swing.JPanel dd;
    private javax.swing.JTable importTable;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<TypeCost> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblPay;
    private javax.swing.JLabel lblProfit;
    private javax.swing.JLabel lblStatistics;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pCosts;
    private javax.swing.JPanel pImport;
    private javax.swing.JPanel pProfit;
    private javax.swing.JPanel pRevenue;
    private javax.swing.JLabel profit;
    private javax.swing.JTable revenueTable;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

}
